### ISSUE TITLE
Version of provided checkpoint file

### ISSUE THREAD

**Issue by MClarkTurner** [babajide07/Redundant-Feature-Pruning-Pytorch-Implementation#2]
I was curious if you knew the version of PyTorch used to generate the provided checkpoint file. It seems that it does not work with the most recent version of PyTorch (1.4.0) and I receive an error that states: 

AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'

**Comment by MClarkTurner** [comment]
I have updated the code to work with PyTorch 1.4 and issued a pull request of the updated code. The authors haven't responded to my earlier comment so I'm not sure how frequently this repo is being monitored. You may need to check the "Pull Request" tab.
